### ISSUE TITLE
The link to the pre-trained SeXception model is not available.

### ISSUE THREAD

**Issue by lizheren** [Nahid1992/CAD_PE#1]
Hi authors,

It is a wonderful work for PE detection. The link to the pre-trained SeXception model is not available. Could you please update it?

Thanks for your kindness.

**Comment by Nahid1992** [comment]
Hello, 

I updated the link. Can you try this?
https://www.dropbox.com/scl/fi/smcbb6xzmq3gsm379cvoi/sexception_imagenet_pretrainedweight.pth.tar?rlkey=nyfltetkacsexwru7m5kfejmb&dl=0

Thanks,
Nahid
